// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package net.netau.vasyoid.utils;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Array)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 elementsCount = 1;</code>
     */
    boolean hasElementsCount();
    /**
     * <code>required int32 elementsCount = 1;</code>
     */
    int getElementsCount();

    /**
     * <code>repeated int32 element = 2;</code>
     */
    java.util.List<java.lang.Integer> getElementList();
    /**
     * <code>repeated int32 element = 2;</code>
     */
    int getElementCount();
    /**
     * <code>repeated int32 element = 2;</code>
     */
    int getElement(int index);
  }
  /**
   * Protobuf type {@code Array}
   */
  public  static final class Array extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Array)
      ArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Array.newBuilder() to construct.
    private Array(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Array() {
      elementsCount_ = 0;
      element_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Array(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              elementsCount_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                element_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              element_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                element_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                element_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = java.util.Collections.unmodifiableList(element_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.internal_static_Array_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.internal_static_Array_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protocol.Array.class, Protocol.Array.Builder.class);
    }

    private int bitField0_;
    public static final int ELEMENTSCOUNT_FIELD_NUMBER = 1;
    private int elementsCount_;
    /**
     * <code>required int32 elementsCount = 1;</code>
     */
    public boolean hasElementsCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 elementsCount = 1;</code>
     */
    public int getElementsCount() {
      return elementsCount_;
    }

    public static final int ELEMENT_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> element_;
    /**
     * <code>repeated int32 element = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getElementList() {
      return element_;
    }
    /**
     * <code>repeated int32 element = 2;</code>
     */
    public int getElementCount() {
      return element_.size();
    }
    /**
     * <code>repeated int32 element = 2;</code>
     */
    public int getElement(int index) {
      return element_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasElementsCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, elementsCount_);
      }
      for (int i = 0; i < element_.size(); i++) {
        output.writeInt32(2, element_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, elementsCount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < element_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element_.get(i));
        }
        size += dataSize;
        size += 1 * getElementList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protocol.Array)) {
        return super.equals(obj);
      }
      Protocol.Array other = (Protocol.Array) obj;

      boolean result = true;
      result = result && (hasElementsCount() == other.hasElementsCount());
      if (hasElementsCount()) {
        result = result && (getElementsCount()
            == other.getElementsCount());
      }
      result = result && getElementList()
          .equals(other.getElementList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasElementsCount()) {
        hash = (37 * hash) + ELEMENTSCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getElementsCount();
      }
      if (getElementCount() > 0) {
        hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getElementList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protocol.Array parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.Array parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.Array parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.Array parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.Array parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.Array parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.Array parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocol.Array parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocol.Array parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protocol.Array parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocol.Array parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocol.Array parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protocol.Array prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Array}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Array)
        Protocol.ArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.internal_static_Array_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.internal_static_Array_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protocol.Array.class, Protocol.Array.Builder.class);
      }

      // Construct using net.netau.vasyoid.utils.Protocol.Array.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        elementsCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.internal_static_Array_descriptor;
      }

      public Protocol.Array getDefaultInstanceForType() {
        return Protocol.Array.getDefaultInstance();
      }

      public Protocol.Array build() {
        Protocol.Array result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protocol.Array buildPartial() {
        Protocol.Array result = new Protocol.Array(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.elementsCount_ = elementsCount_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = java.util.Collections.unmodifiableList(element_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.element_ = element_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocol.Array) {
          return mergeFrom((Protocol.Array)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protocol.Array other) {
        if (other == Protocol.Array.getDefaultInstance()) return this;
        if (other.hasElementsCount()) {
          setElementsCount(other.getElementsCount());
        }
        if (!other.element_.isEmpty()) {
          if (element_.isEmpty()) {
            element_ = other.element_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureElementIsMutable();
            element_.addAll(other.element_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasElementsCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protocol.Array parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protocol.Array) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int elementsCount_ ;
      /**
       * <code>required int32 elementsCount = 1;</code>
       */
      public boolean hasElementsCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 elementsCount = 1;</code>
       */
      public int getElementsCount() {
        return elementsCount_;
      }
      /**
       * <code>required int32 elementsCount = 1;</code>
       */
      public Builder setElementsCount(int value) {
        bitField0_ |= 0x00000001;
        elementsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 elementsCount = 1;</code>
       */
      public Builder clearElementsCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        elementsCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> element_ = java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          element_ = new java.util.ArrayList<java.lang.Integer>(element_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getElementList() {
        return java.util.Collections.unmodifiableList(element_);
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public int getElementCount() {
        return element_.size();
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public int getElement(int index) {
        return element_.get(index);
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public Builder setElement(
          int index, int value) {
        ensureElementIsMutable();
        element_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public Builder addElement(int value) {
        ensureElementIsMutable();
        element_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public Builder addAllElement(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureElementIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, element_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 element = 2;</code>
       */
      public Builder clearElement() {
        element_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Array)
    }

    // @@protoc_insertion_point(class_scope:Array)
    private static final Protocol.Array DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protocol.Array();
    }

    public static Protocol.Array getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Array>
        PARSER = new com.google.protobuf.AbstractParser<Array>() {
      public Array parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Array(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Array> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Array> getParserForType() {
      return PARSER;
    }

    public Protocol.Array getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 port = 1;</code>
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 1;</code>
     */
    int getPort();

    /**
     * <code>required int32 arraySize = 2;</code>
     */
    boolean hasArraySize();
    /**
     * <code>required int32 arraySize = 2;</code>
     */
    int getArraySize();

    /**
     * <code>required int32 clientsCount = 3;</code>
     */
    boolean hasClientsCount();
    /**
     * <code>required int32 clientsCount = 3;</code>
     */
    int getClientsCount();

    /**
     * <code>required int32 delta = 4;</code>
     */
    boolean hasDelta();
    /**
     * <code>required int32 delta = 4;</code>
     */
    int getDelta();

    /**
     * <code>required int32 requestsCount = 5;</code>
     */
    boolean hasRequestsCount();
    /**
     * <code>required int32 requestsCount = 5;</code>
     */
    int getRequestsCount();
  }
  /**
   * Protobuf type {@code TestTask}
   */
  public  static final class TestTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestTask)
      TestTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestTask.newBuilder() to construct.
    private TestTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestTask() {
      port_ = 0;
      arraySize_ = 0;
      clientsCount_ = 0;
      delta_ = 0;
      requestsCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              arraySize_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientsCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              delta_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              requestsCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.internal_static_TestTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.internal_static_TestTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protocol.TestTask.class, Protocol.TestTask.Builder.class);
    }

    private int bitField0_;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    /**
     * <code>required int32 port = 1;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 port = 1;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int ARRAYSIZE_FIELD_NUMBER = 2;
    private int arraySize_;
    /**
     * <code>required int32 arraySize = 2;</code>
     */
    public boolean hasArraySize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 arraySize = 2;</code>
     */
    public int getArraySize() {
      return arraySize_;
    }

    public static final int CLIENTSCOUNT_FIELD_NUMBER = 3;
    private int clientsCount_;
    /**
     * <code>required int32 clientsCount = 3;</code>
     */
    public boolean hasClientsCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 clientsCount = 3;</code>
     */
    public int getClientsCount() {
      return clientsCount_;
    }

    public static final int DELTA_FIELD_NUMBER = 4;
    private int delta_;
    /**
     * <code>required int32 delta = 4;</code>
     */
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 delta = 4;</code>
     */
    public int getDelta() {
      return delta_;
    }

    public static final int REQUESTSCOUNT_FIELD_NUMBER = 5;
    private int requestsCount_;
    /**
     * <code>required int32 requestsCount = 5;</code>
     */
    public boolean hasRequestsCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 requestsCount = 5;</code>
     */
    public int getRequestsCount() {
      return requestsCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArraySize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientsCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelta()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestsCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, arraySize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, clientsCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, delta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, requestsCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, arraySize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clientsCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, delta_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, requestsCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Protocol.TestTask)) {
        return super.equals(obj);
      }
      Protocol.TestTask other = (Protocol.TestTask) obj;

      boolean result = true;
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && (hasArraySize() == other.hasArraySize());
      if (hasArraySize()) {
        result = result && (getArraySize()
            == other.getArraySize());
      }
      result = result && (hasClientsCount() == other.hasClientsCount());
      if (hasClientsCount()) {
        result = result && (getClientsCount()
            == other.getClientsCount());
      }
      result = result && (hasDelta() == other.hasDelta());
      if (hasDelta()) {
        result = result && (getDelta()
            == other.getDelta());
      }
      result = result && (hasRequestsCount() == other.hasRequestsCount());
      if (hasRequestsCount()) {
        result = result && (getRequestsCount()
            == other.getRequestsCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasArraySize()) {
        hash = (37 * hash) + ARRAYSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getArraySize();
      }
      if (hasClientsCount()) {
        hash = (37 * hash) + CLIENTSCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getClientsCount();
      }
      if (hasDelta()) {
        hash = (37 * hash) + DELTA_FIELD_NUMBER;
        hash = (53 * hash) + getDelta();
      }
      if (hasRequestsCount()) {
        hash = (37 * hash) + REQUESTSCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getRequestsCount();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Protocol.TestTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.TestTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.TestTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.TestTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.TestTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Protocol.TestTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Protocol.TestTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocol.TestTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocol.TestTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Protocol.TestTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Protocol.TestTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Protocol.TestTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Protocol.TestTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestTask)
        Protocol.TestTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.internal_static_TestTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.internal_static_TestTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Protocol.TestTask.class, Protocol.TestTask.Builder.class);
      }

      // Construct using net.netau.vasyoid.utils.Protocol.TestTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arraySize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientsCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        delta_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        requestsCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.internal_static_TestTask_descriptor;
      }

      public Protocol.TestTask getDefaultInstanceForType() {
        return Protocol.TestTask.getDefaultInstance();
      }

      public Protocol.TestTask build() {
        Protocol.TestTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Protocol.TestTask buildPartial() {
        Protocol.TestTask result = new Protocol.TestTask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.arraySize_ = arraySize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientsCount_ = clientsCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.delta_ = delta_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestsCount_ = requestsCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Protocol.TestTask) {
          return mergeFrom((Protocol.TestTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Protocol.TestTask other) {
        if (other == Protocol.TestTask.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasArraySize()) {
          setArraySize(other.getArraySize());
        }
        if (other.hasClientsCount()) {
          setClientsCount(other.getClientsCount());
        }
        if (other.hasDelta()) {
          setDelta(other.getDelta());
        }
        if (other.hasRequestsCount()) {
          setRequestsCount(other.getRequestsCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPort()) {
          return false;
        }
        if (!hasArraySize()) {
          return false;
        }
        if (!hasClientsCount()) {
          return false;
        }
        if (!hasDelta()) {
          return false;
        }
        if (!hasRequestsCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Protocol.TestTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Protocol.TestTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int port_ ;
      /**
       * <code>required int32 port = 1;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 1;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        onChanged();
        return this;
      }

      private int arraySize_ ;
      /**
       * <code>required int32 arraySize = 2;</code>
       */
      public boolean hasArraySize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 arraySize = 2;</code>
       */
      public int getArraySize() {
        return arraySize_;
      }
      /**
       * <code>required int32 arraySize = 2;</code>
       */
      public Builder setArraySize(int value) {
        bitField0_ |= 0x00000002;
        arraySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arraySize = 2;</code>
       */
      public Builder clearArraySize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        arraySize_ = 0;
        onChanged();
        return this;
      }

      private int clientsCount_ ;
      /**
       * <code>required int32 clientsCount = 3;</code>
       */
      public boolean hasClientsCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 clientsCount = 3;</code>
       */
      public int getClientsCount() {
        return clientsCount_;
      }
      /**
       * <code>required int32 clientsCount = 3;</code>
       */
      public Builder setClientsCount(int value) {
        bitField0_ |= 0x00000004;
        clientsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientsCount = 3;</code>
       */
      public Builder clearClientsCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientsCount_ = 0;
        onChanged();
        return this;
      }

      private int delta_ ;
      /**
       * <code>required int32 delta = 4;</code>
       */
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 delta = 4;</code>
       */
      public int getDelta() {
        return delta_;
      }
      /**
       * <code>required int32 delta = 4;</code>
       */
      public Builder setDelta(int value) {
        bitField0_ |= 0x00000008;
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 delta = 4;</code>
       */
      public Builder clearDelta() {
        bitField0_ = (bitField0_ & ~0x00000008);
        delta_ = 0;
        onChanged();
        return this;
      }

      private int requestsCount_ ;
      /**
       * <code>required int32 requestsCount = 5;</code>
       */
      public boolean hasRequestsCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 requestsCount = 5;</code>
       */
      public int getRequestsCount() {
        return requestsCount_;
      }
      /**
       * <code>required int32 requestsCount = 5;</code>
       */
      public Builder setRequestsCount(int value) {
        bitField0_ |= 0x00000010;
        requestsCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requestsCount = 5;</code>
       */
      public Builder clearRequestsCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestsCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestTask)
    }

    // @@protoc_insertion_point(class_scope:TestTask)
    private static final Protocol.TestTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Protocol.TestTask();
    }

    public static Protocol.TestTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TestTask>
        PARSER = new com.google.protobuf.AbstractParser<TestTask>() {
      public TestTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestTask> getParserForType() {
      return PARSER;
    }

    public Protocol.TestTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Array_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Array_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\"/\n\005Array\022\025\n\relementsCoun" +
      "t\030\001 \002(\005\022\017\n\007element\030\002 \003(\005\"g\n\010TestTask\022\014\n\004" +
      "port\030\001 \002(\005\022\021\n\tarraySize\030\002 \002(\005\022\024\n\014clients" +
      "Count\030\003 \002(\005\022\r\n\005delta\030\004 \002(\005\022\025\n\rrequestsCo" +
      "unt\030\005 \002(\005B\034\n\021net.netau.vasyoidB\007Request"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Array_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Array_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Array_descriptor,
        new java.lang.String[] { "ElementsCount", "Element", });
    internal_static_TestTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TestTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestTask_descriptor,
        new java.lang.String[] { "Port", "ArraySize", "ClientsCount", "Delta", "RequestsCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
